# -*- coding: utf-8 -*-
"""Agglomerative.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XOAMbRJuXMwgCJqKwBwwfCi8GoxrJNCS
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage

from google.colab import files
uploaded = files.upload()
df = pd.read_csv('agglodata.csv', sep=',', header=None)
print(df.values)
arr = np.array(df.values)

#X = np.array([[0,9,3,6,11],[9,0,7,5,10],[3,7,0,9,2],[6,5,9,0,8],[11,10,2,8,0],])
X = np.array(df.values)

import matplotlib.pyplot as plt

labels = range(1, 6)
plt.figure(figsize=(10, 3))
plt.subplots_adjust(bottom=0.1)
plt.scatter(X[:,0],X[:,1], label='True Position')

for label, x, y in zip(labels, X[:, 0], X[:, 1]):
    plt.annotate(
        label,
        xy=(x, y), xytext=(-3, 3),
        textcoords='offset points', ha='right', va='bottom')
plt.show()

linked = linkage(X, 'single')

labelList = range(1, 6)

plt.figure(figsize=(10, 3))
dendrogram(linked,
            orientation='top',
            labels=labelList,
            distance_sort='descending',
            show_leaf_counts=True)
plt.show()

linked = linkage(X, 'complete')

labelList = range(1, 6)

plt.figure(figsize=(10, 3))
dendrogram(linked,
            orientation='top',
            labels=labelList,
            distance_sort='descending',
            show_leaf_counts=True)
plt.show()

linked = linkage(X, 'average')

labelList = range(1, 6)

plt.figure(figsize=(10, 3))
dendrogram(linked,
            orientation='top',
            labels=labelList,
            distance_sort='descending',
            show_leaf_counts=True)
plt.show()

